### ISSUE TITLE
Challenge: Subarray sum

### ISSUE THREAD

**Issue by Fahim-Ahmad** [MIT-Emerging-Talent/deadline-gamblers#16]
Write a python function to sum the elements of a sub-array from a given array.

**Comment by adel-batal** [comment]
Hello @Fahim-Ahmad, Shouldn't your issues be `in review` instead of closed?

**Comment by adel-batal** [comment]
@Fahim-Ahmad Please reopen and add to project and milestone, then put the tasks in the `in review` column in the project board, same goes for your other 4 issues. Let me know if you need any help.

**Comment by Fahim-Ahmad** [comment]
Thank you @adel-batal . I didn't know this earlier : )
I already finished the coding part, but I re-open it until it is reviewed by any of us.
